cpu_prefix_to_brand = {
	'1.1GigaPro': "VIA",
	'4800S': 'AMD',
	'A10 ': 'AMD',
	'A10-': 'AMD',
	'A100': 'Intel',
	'A110': 'Intel',
	'A12-9800': 'AMD',
	'A4': 'AMD',
	'A6': 'AMD',
	'A8': 'AMD',
	'A9': 'AMD',
	'Athlon': 'AMD',
	'Atom': 'Intel',
	'Aubrey': 'Intel',
	'C-': 'AMD',
	'C3': 'VIA',
	'Celeron': 'Intel',
	'Centaur': 'VIA',
	'Core': 'Intel',
	'E-': 'AMD',
	'E1-': 'AMD',
	'E2-': 'AMD',
	'EPYC': 'AMD',
	'FirePro': 'AMD',
	'FX': 'AMD',
	'GX': 'AMD',
	'K6-': 'AMD',
	'Mobile Athlon': 'AMD',
	'Mobile Pentium': 'Intel',
	'Nano': 'VIA',
	'Opteron': 'AMD',
	'Pentium': 'Intel',
	'Phenom': 'AMD',
	'Processor': 'Intel',
	'PRO': 'AMD',
	'Ryzen': 'AMD',
	'Sempron': 'AMD',
	'Steam': 'AMD',
	'Threadripper': 'AMD',
	'Turion': 'AMD',
	'Xeon': 'Intel',
	'Z-': 'AMD',
}
